### PR TITLE
Make bash scripts safer

### PR DESCRIPTION
**Pull request by VladRassokhin**
That would help detect build problems earlier than having empty artifacts like in https://youtrack.jetbrains.com/issue/JBR-4451

### CODE REVIEW

**Comment by vprovodin** [comment]
at the exit we should do some actions (see do_exit in common.sh). Will it be done in case of set -euo pipefail ?

**Comment by VladRassokhin** [comment]
Hopefully it would work. Would be better to replace such function with with `trap`, but not now.

**Comment by vprovodin** [comment]
integrated, squashed into one commit

**Comment by NikitkoCent** [comment]
@vprovodin Should we also forward-port this to `main` / `jbr-dev` branch?

**Comment by vprovodin** [comment]
yes we should. It is still in progress.

**Comment by vprovodin** [comment]
ported into `main`

**Pull request closed without merging**
