### PR TITLE
JBR-7586 Fix closing menus in a custom title bar

### PR DESCRIPTION
**Pull request by stachenov**
The problem: we add a menu bar to a custom title bar, the user clicks a menu, it expands, then the user clicks again, the menu stays open.

The cause: the click causes the window to be ungrabbed, because it's a click on the frame decorations. Ungrabbing the frame causes the menu to close, just like if the user clicked on an empty area. Then the click reaches the menu and it reopens.

The fix: just don't ungrab if the native actions are disabled. Let the components to handle clicks normally, as if they're located in the client area.

### CODE REVIEW

**Comment by YaaZ** [comment]
Looks good, that's how I would fix it too. However, this is a very fragile matter, hope this doesn't break something else...

**Review by YaaZ — APPROVED** [review]

**Comment by YaaZ** [comment]
@stachenov could you rebase your branch over fresh main, please?

**Review by OnePatchGuy — APPROVED** [review]
Looks good, let's wait for the testing results.

**Review by OnePatchGuy — CHANGES_REQUESTED** [review]
@stachenov, the added test consistently fails on Ubuntu 20.04, 22.04 with the following error:
```java
JMenuClickToCloseTest
       Failed.
       Execution failed: `main' threw exception: java.lang.reflect.InvocationTargetException
     System error from suite jb/javax/swing/CustomTitleBar/JMenuClickToCloseTest.java: java.lang.reflect.InvocationTargetException
      at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1381)
      at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1356)
      at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
      at JMenuClickToCloseTest.main(JMenuClickToCloseTest.java:59)
      at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
      at java.base/java.lang.reflect.Method.invoke(Method.java:573)
      at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
      at java.base/java.lang.Thread.run(Thread.java:1575)
    Caused by: java.lang.NullPointerException: Cannot invoke "com.jetbrains.WindowDecorations.createCustomTitleBar()" because the return value of "com.jetbrains.JBR.getWindowDecorations()" is null
      at JMenuClickToCloseTest.prepareUI(JMenuClickToCloseTest.java:108)
      at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
      at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
      at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
      at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
      at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
      at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
      at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
      at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
      at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
      at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
      at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
      at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
      at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
    
    JavaTest Message: Test threw exception: java.lang.reflect.InvocationTargetException
    JavaTest Message: shutting down test
    
    STATUS:Failed.`main' threw exception: java.lang.reflect.InvocationTargetException
```

**Comment by stachenov** [comment]
Ugh. OK, I guess I'll just change it to skip the test if the custom title bar isn't supported. I think that's better than to hardcode the OS.

**Comment by stachenov** [comment]
Added a check to skip the test if custom window decorations aren't supported.

**Comment by YaaZ** [comment]
@stachenov there is a merge conflict with `main`

**Comment by stachenov** [comment]
Yes, I haven't figured that this was already merged. Fixed.

**Comment by NikitkoCent** [comment]
Pushed the new commit to main and squashed it with the initial one. So, another round of CI testing...

**Pull request closed without merging**
