### PR TITLE
Update 21.0.2

### PR DESCRIPTION
**Pull request by vprovodin**
Update to the latest OpenJDK release version 21.0.2 (jdk-21.0.2+13, jdk-21.0.2-ga)

### CODE REVIEW

**Comment by vprovodin** [comment]
@avu Could you please apply 8304825: _MacOS metal pipeline - window isn't painted if created during display sleep_ ?

**Comment by vprovodin** [comment]
@bourgesl Could you please check 8316741: _BasicStroke.createStrokedShape miter-limits failing on small shapes_?

**Comment by vprovodin** [comment]
@JB-Dmitry The change 8300727: _java/awt/List/ListGarbageCollectionTest/AwtListGarbageCollectionTest.java failed with "List wasn't garbage collected"_  was applied instead of _make AwtListGarbageCollectionTest pass reliably_

**Comment by bourgesl** [comment]
Looks good, jb21 has version 0.9.4.7, good.

**Comment by JB-Dmitry** [comment]
@vprovodin If I'm not mistaken, 8300727 fix has replaced JBR-specific fix much earlier - I see corresponding commit made in our repo on Apr 09 2023.
Just in case, that's expected.

**Pull request merged**
