### PR TITLE
Cache results of font-config pattern search for reuse

### PR DESCRIPTION
**Pull request by osialr**
This is a potential fix for #84.  libfontmanager invokes the fontconfig matcher very often, especially on editor font-size. The implementation caches the results of the calls.

On my system, each call to match takes between 10-20 ms, with a few >100ms.  Kubuntu + libreoffice exacerbates the problem, because it installs a lot of fonts and rules.  But even on a minimal install of ubuntu, this should help because each call takes 1-10ms.

See [IDEA-287246](https://youtrack.jetbrains.com/issue/IDEA-287246) for more debug diagnostics.

### CODE REVIEW

**Comment by osialr** [comment]
@avu I have signed the CLA.

You can change NUM_CACHED_VALUES to 0 to disable the caching mechanism to compare the performance.  I choose the value of 8 empirically based on what smoothed out the UI sufficiently without frequent eviction.

I didn't try tuning the Pattern to FcFontMatch.  Maybe there is an improved pattern that quickly retrieves the required values.

**Review by avu — APPROVED** [review]

**Comment by avu** [comment]
@osialr the changes look good, I've run commit testing and pushed them into JBR11 master

**Comment by osialr** [comment]
Great.  I'm glad to help.

**Comment by avu** [comment]
@osialr thank you very much for your help!

**Pull request merged**
