### PR TITLE
vpr/jbr21_JBR-7015

### PR DESCRIPTION
**Pull request by vprovodin**
JBR-7015 Rebase JBR21 on top of OpenJDK 21.0.3

There were the following conflicts
| 21u                                                                                                  | conflicts with jbr21                                                                                                                     | to review          | comment                                                    |
|:-----------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------|:-------------------|:-----------------------------------------------------------|
| 8304825: MacOS metal pipeline - window isn't painted if created during display sleep                 | JBR-4959 [macOS Ventura] Screen flickering after OS update when IDE is full screen                                                       | @avu               | applied with respect to the changes introduced by JBR-4959 |
| 8316229: Enhance class initialization logging                                                        | JBR-5183 pre-dcevm17 squashed commits                                                                                                    | @vladimir.dvorak   | the resolution was to combine both changes.                |
| 8317228: GC: Make TestXXXHeapSizeFlags use createTestJvm                                             | JBR-3572 Wayland: java/awt/Window/WindowTitleVisibleTest/WindowTitleVisibleTestLinuxGnome.java: title bar shown and hidden are the same. | @maxim.kartashev   | the resolution was to combine both changes.                | 
| 8315097: Rename createJavaProcessBuilder                                                             | JBR-3793 Accept unrecognized options and make them available in Java                                                                     | @maxim.kartashev   | the resolution was to combine both changes.                |
| ---                                                                                                  | JBR-4203 test/hotspot/jtreg/compiler/arguments: Option should be unknown (non-X86CPU)                                                    | @maxim.kartashev   | ---                                                        |
| ---                                                                                                  | JBR-4020 Test ObsoleteFlagErrorMessage fails after +IgnoreUnrecognizedVMOptions has become the default                                   | @maxim.kartashev   | ---                                                        |
| 8319103: Popups that request focus are not shown on Linux with Wayland                               | JBR-5661 Wayland: implement heavy-weight popup windows                                                                                   | @maxim.kartashev   | applied with respect to the changes introduced by JBR-5661 |
| 8317771: [macos14] Expand/collapse a JTree using keyboard freezes the application in macOS 14 Sonoma | JBR-3775 Optimize the algorithm for obtaining tree elements                                                                              | @nikita.provotorov | allow-empty                                                |

### CODE REVIEW

**Comment by mkartashev** [comment]
@vprovodin `8315097: Rename createJavaProcessBuilder` requires this commit or else some JBR-specific tests will not compile:
```
commit b78debd1581afe991b66752cb456ee3bfefd37ec
Author: Maxim Kartashev <maxim.kartashev@jetbrains.com>
Date:   Mon Oct 30 13:22:15 2023 +0400

    JBR-6247 Update JBR-specific tests after JDK-8314823
```

**Comment by vprovodin** [comment]
@mkartashev the changes related to JBR-6247 was added into this PR

**Review by mkartashev — APPROVED** [review]

**Comment by YaaZ** [comment]
@vprovodin I don't understand, what kind of conflict was between "8316229: Enhance class initialization logging", which is in HotSpot and "fixup! JBR-5124 Rewrite custom decorations support", which is in AWT?

**Comment by vprovodin** [comment]
> @vprovodin I don't understand, what kind of conflict was between "8316229: Enhance class initialization logging", which is in HotSpot and "fixup! JBR-5124 Rewrite custom decorations support", which is in AWT?

@YaaZ, Sorry it is my fault, actually it was a conflict with the changes related to DCEVM [JBR-5183](https://youtrack.jetbrains.com/issue/JBR-5183/apply-DCEVM-to-jbr21) pre-dcevm17 squashed commits

**Review by avu — APPROVED** [review]
LGTM

**Pull request closed without merging**
